"""Render extracted schema into a zsh _compdef completion script."""
from __future__ import annotations

from typing import Any

VALUE_HINT_TO_ZSH = {
    "file": "_files",
    "dir": "_files -/",
    "directory": "_files -/",
    "command": "_command_names",
    "host": "_hosts",
    "user": "_users",
    "branch": "__git_branch_names 2>/dev/null || _message branch",
    "integer": "_message number",
    "string": "",
    "enum": "",
}


def _zsh_escape(s: str) -> str:
    if s is None:
        return ""
    return s.replace("\\", "\\\\").replace("'", "''").replace("[", "\\[").replace("]", "\\]").replace(":", "\\:")


def _action_for(flag: dict[str, Any]) -> str:
    if not flag.get("takes_value"):
        return ""
    choices = flag.get("choices") or []
    if choices:
        joined = " ".join(_zsh_escape(c) for c in choices)
        return f":value:({joined})"
    hint = (flag.get("value_hint") or "string").lower()
    action = VALUE_HINT_TO_ZSH.get(hint, "")
    label = _zsh_escape(hint or "value")
    return f":{label}:{action}".rstrip(":")


def _flag_spec(flag: dict[str, Any]) -> str:
    long = flag.get("long") or ""
    short = flag.get("short") or ""
    desc = _zsh_escape(flag.get("description") or "")
    action = _action_for(flag)

    forms = [f for f in (short, long) if f]
    if not forms:
        return ""
    if len(forms) == 2:
        head = "{" + ",".join(forms) + "}"
        exclusion = "(" + " ".join(forms) + ")"
        return f"'{exclusion}'{head}'[{desc}]{action}'"
    return f"'{forms[0]}[{desc}]{action}'"


def _positional_spec(pos: dict[str, Any], idx: int) -> str:
    name = _zsh_escape(pos.get("name") or f"arg{idx}")
    hint = (pos.get("value_hint") or "string").lower()
    action = VALUE_HINT_TO_ZSH.get(hint, "")
    quantifier = "*" if pos.get("repeatable") else f"{idx}"
    return f"'{quantifier}:{name}:{action}'".rstrip("'") + "'"


def _has_subcommands(node: dict[str, Any]) -> bool:
    return bool(node.get("subcommands"))


def _render_node(node: dict[str, Any], func_name: str, indent: str = "  ") -> tuple[str, list[str]]:
    """Return (function body, list of child function definitions)."""
    flags = node.get("flags") or []
    positionals = node.get("positionals") or []
    subs = node.get("subcommands") or []

    lines: list[str] = []
    lines.append(f"{func_name}() {{")
    lines.append(f"{indent}local curcontext=$curcontext state line ret=1")
    lines.append(f"{indent}local -a args")
    lines.append(f"{indent}args=(")

    for f in flags:
        spec = _flag_spec(f)
        if spec:
            lines.append(f"{indent}{indent}{spec}")

    if subs:
        lines.append(f"{indent}{indent}'1: :->cmds'")
        lines.append(f"{indent}{indent}'*::arg:->args'")
    else:
        for i, p in enumerate(positionals, start=1):
            lines.append(f"{indent}{indent}{_positional_spec(p, i)}")

    lines.append(f"{indent})")
    lines.append(f"{indent}_arguments -C $args && ret=0")

    children_defs: list[str] = []
    if subs:
        lines.append(f"{indent}case $state in")
        lines.append(f"{indent}{indent}cmds)")
        sub_descs = []
        for s in subs:
            sname = s.get("name") or ""
            sdesc = _zsh_escape(s.get("description") or "")
            if sname:
                sub_descs.append(f"'{_zsh_escape(sname)}:{sdesc}'")
        lines.append(f"{indent}{indent}{indent}local -a subcmds")
        lines.append(f"{indent}{indent}{indent}subcmds=({' '.join(sub_descs)})")
        lines.append(f"{indent}{indent}{indent}_describe 'command' subcmds && ret=0")
        lines.append(f"{indent}{indent};;")
        lines.append(f"{indent}{indent}args)")
        lines.append(f"{indent}{indent}{indent}case $line[1] in")
        for s in subs:
            sname = s.get("name") or ""
            if not sname:
                continue
            child_fn = f"{func_name}_{sname.replace('-', '_')}"
            lines.append(f"{indent}{indent}{indent}{indent}{sname}) {child_fn} ;;")
            body, more = _render_node(s, child_fn, indent)
            children_defs.append(body)
            children_defs.extend(more)
        lines.append(f"{indent}{indent}{indent}esac")
        lines.append(f"{indent}{indent};;")
        lines.append(f"{indent}esac")

    lines.append(f"{indent}return ret")
    lines.append("}")
    return "\n".join(lines), children_defs


def render_zsh(schema: dict[str, Any]) -> str:
    cmd = schema.get("name") or "cmd"
    safe_cmd = cmd.replace("-", "_")
    root_fn = f"_{safe_cmd}"
    body, children = _render_node(schema, root_fn)

    header = (
        f"#compdef {cmd}\n"
        f"# Generated by completion-ai. Review before installing.\n"
        f"# Move to a directory on $fpath (e.g. ~/.zsh/completions/_{cmd}),\n"
        f"# then run: autoload -U compinit && compinit\n"
    )
    parts = [header, body, *children, f"{root_fn} \"$@\""]
    return "\n\n".join(parts) + "\n"
